management:
  endpoint:
    health:
      enabled: false
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        exclude: '*'
      base-path: /
      path_mapping:
        prometheus: metrics
        metrics: dementions
server:
  port: 7001
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 0
spring:
  application:
    name: biz-dof
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
utils:
  http:
    sendfalcon: false
external:
  domain: hostlingbackend.guazi.com
